-- 기존 테이블 삭제 (자식 → 부모 순서, CASCADE CONSTRAINTS)

BEGIN EXECUTE IMMEDIATE 'DROP TABLE BID CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ENROLLMENT CASCADE CONSTRAINTS';  EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BASKETITEM CASCADE CONSTRAINTS';  EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TIMESLOT CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUCTION CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BASKET CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SECTION CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COURSE CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/


CREATE TABLE STUDENT (
    STUDENT_ID       NUMBER(10)            NOT NULL,
    NAME             VARCHAR2(50)          NOT NULL,
    DEPARTMENT       VARCHAR2(50),
    GRADE            NUMBER(2),                          -- 학년
    PASSWORD         VARCHAR2(100)         NOT NULL,
    MAX_CREDITS      NUMBER(3)             DEFAULT 18  NOT NULL,
    MAX_POINT        NUMBER(10)            DEFAULT 0   NOT NULL,
    CONSTRAINT CK_STU_CREDITS  CHECK (MAX_CREDITS >= 0),
    CONSTRAINT CK_STU_POINTS   CHECK (MAX_POINT >= 0),
    PRIMARY KEY(STUDENT_ID)
);

CREATE TABLE COURSE (
    COURSE_ID    VARCHAR2(10)      NOT NULL,
    COURSE_NAME  VARCHAR2(100)     NOT NULL,
    DEPARTMENT   VARCHAR2(50),
    CREDITS      NUMBER(2)         NOT NULL,
    CAPACITY     NUMBER(5),
    SEMESTER     VARCHAR2(6),
    YEAR         NUMBER(4),
    CONSTRAINT CK_COURSE_CREDITS  CHECK (CREDITS >= 0),
    CONSTRAINT CK_COURSE_CAP      CHECK (CAPACITY >= 0),
    PRIMARY KEY(COURSE_ID)
);

CREATE TABLE SECTION (
    SECTION_ID      VARCHAR2(14)       NOT NULL,
    SECTION_NUMBER  NUMBER(3)          NOT NULL,           -- 분반 번호
    PROFESSOR       VARCHAR2(50),
    CAPACITY        NUMBER(5),
    CLASSROOM       VARCHAR2(50),
    COURSE_ID       VARCHAR2(10)       NOT NULL,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID) ON DELETE CASCADE,
    CONSTRAINT CK_SECTION_CAP     CHECK (CAPACITY >= 0),
    UNIQUE (COURSE_ID, SECTION_NUMBER),
    PRIMARY KEY(SECTION_ID)
);

CREATE TABLE TIMESLOT (
    DAY         VARCHAR2(3)        NOT NULL,           -- MON,TUE,WED,THU,FRI,SAT,SUN
    START_TIME  NUMBER(4)          NOT NULL,           -- 0~1439분
    END_TIME    NUMBER(4)          NOT NULL,           -- 1~1440분
    SECTION_ID  VARCHAR2(14)       NOT NULL,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    CONSTRAINT CK_TS_DAY    CHECK (DAY IN ('MON','TUE','WED','THU','FRI','SAT','SUN')),
    CONSTRAINT CK_TS_T1     CHECK (START_TIME BETWEEN 0 AND 1439),
    CONSTRAINT CK_TS_T2     CHECK (END_TIME   BETWEEN 1 AND 1440),
    CONSTRAINT CK_TS_RANGE  CHECK (START_TIME < END_TIME),
    PRIMARY KEY (DAY, START_TIME, END_TIME, SECTION_ID)
);

CREATE TABLE BASKET (
    BASKET_ID   VARCHAR2(10)   NOT NULL,
    STUDENT_ID  NUMBER(10)     NOT NULL,
    FOREIGN KEY (STUDENT_ID)   REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE,
    PRIMARY KEY (BASKET_ID)
);

CREATE TABLE BASKETITEM (
    REGISTRATION_TIME  DATE            DEFAULT SYSDATE,
    STATUS             VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL, -- PENDING/SUCCESS/FAILED
    PROCESSED_TIME     DATE            DEFAULT SYSDATE,
    REASON             VARCHAR2(1000),
    BASKET_ID          VARCHAR2(10)    NOT NULL,
    SECTION_ID         VARCHAR2(14)    NOT NULL,
    FOREIGN KEY (BASKET_ID) REFERENCES BASKET(BASKET_ID) ON DELETE CASCADE,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    CONSTRAINT CK_BASKETITEM_STATUS CHECK (STATUS IN ('PENDING','SUCCESS','FAILED')),
    PRIMARY KEY (BASKET_ID, SECTION_ID)
);

CREATE TABLE ENROLLMENT (
    ENROLLMENT_ID    VARCHAR2(10)   NOT NULL,
    ENROLLMENT_SOURCE VARCHAR2(13)  NOT NULL,  -- FROM_BASKET/FROM_AUCTION
    POINTS_USED      NUMBER(10)   DEFAULT 0,
    ENROLLMENT_TIME  DATE           DEFAULT SYSDATE NOT NULL,
    STUDENT_ID       NUMBER(10)     NOT NULL,
    SECTION_ID       VARCHAR2(14)   NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    CONSTRAINT CK_ENR_SRC    CHECK (ENROLLMENT_SOURCE IN ('FROM_BASKET','FROM_AUCTION')),
    CONSTRAINT CK_ENR_POINTS CHECK (POINTS_USED >= 0),
    PRIMARY KEY (ENROLLMENT_ID),
    CONSTRAINT UK_ENR_UNQ UNIQUE (STUDENT_ID, SECTION_ID)
);

CREATE TABLE AUCTION (
    AUCTION_ID      VARCHAR2(10)   NOT NULL,
    START_TIME      DATE           NOT NULL,
    END_TIME        DATE,
    STATUS          VARCHAR2(12)   DEFAULT 'PENDING' NOT NULL,   -- PENDING/ACTIVE/COMPLETED/CANCELLED
    AVAILABLE_SLOTS NUMBER(5),
    CREATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    SECTION_ID      VARCHAR2(14)   NOT NULL,
    FOREIGN KEY (SECTION_ID) REFERENCES SECTION(SECTION_ID) ON DELETE CASCADE,
    CONSTRAINT CK_AUC_STATUS CHECK (STATUS IN ('PENDING','ACTIVE','COMPLETED','CANCELLED')),
    CONSTRAINT CK_AUC_SLOTS  CHECK (AVAILABLE_SLOTS >= 0),
    PRIMARY KEY (AUCTION_ID)
);

CREATE TABLE BID (
    BID_SEQUENCE   VARCHAR2(10)    NOT NULL,
    BID_AMOUNT     NUMBER(10)      NOT NULL,
    BID_TIME       DATE            DEFAULT SYSDATE NOT NULL,
    IS_SUCCESSFUL  CHAR(1)         DEFAULT 'N' NOT NULL,  -- Y/N
    AUCTION_ID     VARCHAR2(10)    NOT NULL,
    STUDENT_ID     NUMBER(10)      NOT NULL,
    FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION(AUCTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE,
    CONSTRAINT CK_BID_AMOUNT CHECK (BID_AMOUNT >= 0),
    CONSTRAINT CK_BID_YN     CHECK (IS_SUCCESSFUL IN ('Y','N')),
    PRIMARY KEY (BID_SEQUENCE)
);

CREATE TABLE LOG (
    LOG_ID       VARCHAR2(10)   NOT NULL,
    ACTION_TYPE  VARCHAR2(15)   NOT NULL,     -- e.g., LOGIN, LOGOUT, AUCTION_OPENED, AUCTION_CLOSED
    TIMESTAMP    DATE           DEFAULT SYSDATE NOT NULL,
    DETAILS      VARCHAR2(1000),
    STUDENT_ID   NUMBER(10),
    AUCTION_ID   VARCHAR2(10),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON DELETE SET NULL,
    FOREIGN KEY (AUCTION_ID) REFERENCES AUCTION(AUCTION_ID) ON DELETE SET NULL,
    PRIMARY KEY (LOG_ID)
);

-- 학생 최대 신청 학점( MAX_CREDITS ) 초과 방지 트리거
-- 동작 시점: ENROLLMENT에 INSERT / STUDENT_ID 또는 SECTION_ID 변경 UPDATE
CREATE OR REPLACE TRIGGER TRG_ENR_MAX_CREDIT
BEFORE INSERT OR UPDATE OF STUDENT_ID, SECTION_ID ON ENROLLMENT
FOR EACH ROW
DECLARE
    v_max         NUMBER;   -- 학생의 최대 학점
    v_current     NUMBER;   -- 현재까지 신청된 학점 합계
    v_new_credits NUMBER;   -- 새로 신청하는 강의의 학점
BEGIN
    -- 1. 학생의 최대 학점 조회
    SELECT MAX_CREDITS
      INTO v_max
      FROM STUDENT
     WHERE STUDENT_ID = :NEW.STUDENT_ID;

    -- 2. 새로 신청하는 분반의 학점 조회
    SELECT c.CREDITS
      INTO v_new_credits
      FROM SECTION s
      JOIN COURSE c ON c.COURSE_ID = s.COURSE_ID
     WHERE s.SECTION_ID = :NEW.SECTION_ID;

    -- 3. 현재까지 신청된 학점 합 (이번 행 제외)
    SELECT NVL(SUM(c.CREDITS), 0)
      INTO v_current
      FROM ENROLLMENT e
      JOIN SECTION s ON s.SECTION_ID = e.SECTION_ID
      JOIN COURSE  c ON c.COURSE_ID  = s.COURSE_ID
     WHERE e.STUDENT_ID = :NEW.STUDENT_ID
       AND ( :NEW.ENROLLMENT_ID IS NULL OR e.ENROLLMENT_ID <> :NEW.ENROLLMENT_ID );

    -- 4. 초과 여부 검사
    IF v_current + v_new_credits > v_max THEN
        RAISE_APPLICATION_ERROR(
            -20011,
            '최대 신청 가능 학점('||v_max||')을 초과합니다. '
            || '현재: '||v_current||'학점, 추가: '||v_new_credits||'학점'
        );
    END IF;
END;
/
SHOW ERRORS;

-- 학생의 총 입찰 포인트 합계가 STUDENT.MAX_POINT 를 초과하지 못하도록 제한
CREATE OR REPLACE TRIGGER TRG_BID_MAX_POINT_TOTAL
BEFORE INSERT OR UPDATE OF BID_AMOUNT, STUDENT_ID ON BID
FOR EACH ROW
DECLARE
    v_max_point   NUMBER;   -- 학생의 총 사용 가능 포인트
    v_total_bid   NUMBER;   -- 학생이 지금까지 입찰한 총 금액(현재 행 제외)
BEGIN
    -- 1. 학생의 MAX_POINT 조회
    SELECT MAX_POINT
      INTO v_max_point
      FROM STUDENT
     WHERE STUDENT_ID = :NEW.STUDENT_ID;

    -- 2. 해당 학생의 현재까지 모든 입찰 금액 합산 (이번 행 제외)
    SELECT NVL(SUM(BID_AMOUNT), 0)
      INTO v_total_bid
      FROM BID
     WHERE STUDENT_ID = :NEW.STUDENT_ID
       AND ( :NEW.BID_SEQUENCE IS NULL OR BID_SEQUENCE <> :NEW.BID_SEQUENCE );

    -- 3. 초과 여부 검사
    IF v_total_bid + :NEW.BID_AMOUNT > v_max_point THEN
        RAISE_APPLICATION_ERROR(
            -20022,
            '총 입찰 포인트('||(v_total_bid + :NEW.BID_AMOUNT)||')가 허용 한도('||v_max_point||')를 초과합니다.'
        );
    END IF;
END;
/
SHOW ERRORS;



























